### ISSUE TITLE
Ease ZeroMQ installation

### ISSUE THREAD

**Issue by steffi-graphdb** [steffi-graphdb/Steffi#1]
ZeroMQ + jzmq java bindings installation is not straight out of the box. There should be a better way to bundle both these dependencies (ex: jzmq as static dependency inside the Java code. cf Gary)

**Comment by nltran** [comment]
This should make use of https://github.com/gaverhae/naughtmq

**Comment by gaverhae** [comment]
Is there a reason why Steffi relies on the (as far as I can see non-existent) jzmq4 package, instead of plain jzmq? What is jzmq4-native?
